### ISSUE TITLE
Critical: running ~help causes hard crash

### ISSUE THREAD

**Issue by torohangupta** [torohangupta/Wall-E#4]
Fix required ASAP - running `~help` command causes hard crash

**Comment by torohangupta** [comment]
On first instance of critical crash, the embed is displayed and then immediately deleted and replaced with the following message in the channel:
`That page doesn't exist!`

With the following error logged to the console
```js
[worker.1]: Running help, requested by <@382893405178691584>
[worker.1]: /app/node_modules/discord.js/src/util/Util.js:406
[worker.1]:     if (typeof data !== 'string') throw new error(errorMessage);
[worker.1]:                                         ^
[worker.1]: 
[worker.1]: RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
[worker.1]:     at Function.verifyString (/app/node_modules/discord.js/src/util/Util.js:406:41)
[worker.1]:     at Function.normalizeField (/app/node_modules/discord.js/src/structures/MessageEmbed.js:432:19)
[worker.1]:     at /app/node_modules/discord.js/src/structures/MessageEmbed.js:453:14
[worker.1]:     at Array.map (<anonymous>)
[worker.1]:     at Function.normalizeFields (/app/node_modules/discord.js/src/structures/MessageEmbed.js:452:8)
[worker.1]:     at MessageEmbed.addFields (/app/node_modules/discord.js/src/structures/MessageEmbed.js:285:42)
[worker.1]:     at commandEmbed (/app/release_public/commands/help.js:300:18)
[worker.1]:     at ReactionCollector.<anonymous> (/app/release_public/commands/help.js:111:52)
[worker.1]:     at ReactionCollector.emit (node:events:406:35)
[worker.1]:     at ReactionCollector.handleCollect (/app/node_modules/discord.js/src/structures/interfaces/Collector.js:108:12) {
[worker.1]:   [Symbol(code)]: 'EMBED_FIELD_VALUE'
[worker.1]: }
[worker.1]: Process exited with status 1
[worker.1]: State changed from up to crashed
```
